### PR TITLE
Alt Bootloader Process + SWD_programming jig

### PR DESCRIPTION
**Pull request by Cydget**
Added some basic instructions for installing bootloader using openocd with and stlink programmer. 
Also added jig/model to allow for solderless bootloader programming.

### CODE REVIEW

**Comment by adamb314** [comment]
Hi Cydget! Thank you for this pull request. I have moved some things around to fit in better with the other documentation. Please have a look so that everything still looks okay before i merge the request.

**Comment by Cydget** [comment]
Looks good to me. There was one other thing I didn't add and forgot to mention. If you strictly follow the build instructions, the Section: Configure-> 2. will fail unless some dependencies are pre installed. 
I know you already have the dependencies.md file, but it might be worth adding a mention to that before the configure portion.
I think the main dependency that failed was python3-gi-cairo. After that was installed the config script ran and installed the other dependencies.
A better option may be to have a requirement.txt file available, so people could do pip3 install -r requirement.txt instead.

**Comment by adamb314** [comment]
Thank you for the feedback! That is strange, because `python3-gi-cairo` is a sub dependency of `python3-gi`... What OS are you using?

**Comment by Cydget** [comment]
Fresh install of Kubuntu 22.04.4. I don't think python3-gi was installed either until I installed python3-gi-cairo. If I followed the dependency file first, I don't think I would have seen issues. Just trying to make it more seamless for others interested in the project.

**Pull request merged**
